version: 2.1

orbs:
  python: circleci/python@1.2
  node: circleci/node@4.7.0

workflows:
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - node/install
      - checkout
      - restore_cache:
          key: build-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Validate Javascript code
          command: |
            git submodule init
            git submodule update
            npm install
            npx eslint js/
            npx eslint modules/
            pip install --upgrade pip
            pip install pylint
            pylint package_chrome.py
      - save_cache:
          key: build-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "/home/circleci/venv"
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: test-reports/
          destination: javascript_app
      - store_artifacts:
          path: /home/circleci/.npm/_logs
          destination: npm_logs

